# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TxfqmwpPjdCDe6z1s8cviMS1hXVdWT2-
"""

import random

# Step 1: Predefined list of 5 words
words = ["python", "code", "alpha", "hangman", "task"]

# Step 2: Randomly select one word
word = random.choice(words)

# Step 3: Create a display with underscores
display = ["_"] * len(word)

# Step 4: Set maximum incorrect guesses
lives = 6
guessed_letters = []

print("🎮 Welcome to Hangman Game!")
print("Guess the word:")
print(" ".join(display))

# Step 5: Game loop
while lives > 0 and "_" in display:
    guess = input("Enter a letter: ").lower()

    # Check if already guessed
    if guess in guessed_letters:
        print("⚠️ You already guessed that letter. Try again.")
        continue

    guessed_letters.append(guess)

    if guess in word:
        print(f"✅ Good guess! '{guess}' is in the word.")
        # Reveal guessed letters
        for i in range(len(word)):
            if word[i] == guess:
                display[i] = guess
    else:
        lives -= 1
        print(f"❌ Wrong guess! You lost a life. Lives left: {lives}")

    print(" ".join(display))

# Step 6: End of game
if "_" not in display:
    print("🎉 Congratulations! You guessed the word:", word)
else:
    print("💀 Game Over! The word was:", word)